version: '3.8'

services:
  db:
    image: postgres:15
    container_name: gym-postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=gymdb
    ports:
      - "5432:5432"
    restart: always